env:
  browser: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint

parserOptions:
  project: ./tsconfig.json

rules:
  '@typescript-eslint/camelcase':
    - error
    - allow:
        - ^\$_
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - varsIgnorePattern: h
  class-methods-use-this: off
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
