references:
  base: &base
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/marp-vue
    steps:
      - run: node --version

      # https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#upgradingdowngrading-yarn
      - run:
          name: Upgrade and configure yarn
          command: |
            sudo -E sh -c 'curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
                           && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
                           && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
                           && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
                           && rm yarn-v$YARN_VERSION.tar.gz'

            [ -n "$YARN_IGNORE_ENGINES" ] && echo '--install.ignore-engines true' >> ~/.yarnrc || true
          environment:
            YARN_VERSION: 1.15.2

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install
      - run: yarn audit

      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

      - run:
          name: Prettier formatting
          command: yarn check:format

      - run:
          name: ESLint
          command: yarn lint:js

      - run:
          name: TypeScript type checking
          command: yarn check:ts

      - run:
          name: Jest
          command: yarn test:coverage --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: tmp/test-results/jest.xml

      - run: yarn codecov

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

version: 2
jobs:
  current:
    <<: *base

  carbon:
    <<: *base
    docker:
      - image: circleci/node:carbon

  erbium:
    <<: *base
    docker:
      - image: circleci/node:12

workflows:
  version: 2
  build:
    jobs:
      - current
      - carbon
      - erbium
